
spring:
  mongodb:
    database: Fitness-App
    uri: mongodb+srv://mohitwadhwani0205:Mohit2105@java-fitness-app.giuaqrk.mongodb.net/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
server:
  port: 8083
rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}