server:
  port: 8081

spring:
  datasource:
    url: "Your URL here"
    username: "Your username here"
    password: "Your password here"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
logging:
  level:
    org.springframework.cloud.gateway: TRACE
